### ISSUE TITLE
Definición de características del proyecto

### ISSUE THREAD

**Issue by FiSaRaff** [mpenacasares/equipo-2-musicStream-data-promoK#9]
SPOTIFY:
Rango de años: 2021 -2023.
Num. canciones: 500 por año.
Géneros: electrónica, latino, pop español, rock español.
Elementos: 
Artista - encontrado en el search inicial que hicimos de prueba. 
Genero musical - ya definido en la propia búsqueda.
Tipo (canción o álbum) - se encuentra en album, album type.
Nombre de la canción o album - encontrado en el search inicial que hicimos de prueba. 
Año de lanzamiento - se encuentra como release date.
Cantidad de canciones en la extracción - dejar para el final.

Extracciones electrónica:
Jupyter por persona con su asignación, luego unir.
Maca probando a sacar todo Latino de manera automática (bucles)

**Comment by mpenacasares** [comment]
update generos: latino, spanish, electronica, rock

**Comment by ArianaPapantonio** [comment]
update años 2021 - 2022
